//! "On this day" memories, generated by a nightly job.

use domus_common::{Error, Result};
use domus_db::Repositories;
use uuid::Uuid;

pub struct MemoryService {
    #[allow(dead_code)]
    repos: Repositories,
}

impl MemoryService {
    pub fn new(repos: Repositories) -> Self {
        Self { repos }
    }

    pub async fn list(&self, user_id: Uuid) -> Result<Vec<domus_db::entities::Memory>> {
        self.repos.memory.create_on_this_day(user_id).await?;
        self.repos.memory.list_for_user(user_id).await
    }

    pub async fn get(&self, id: Uuid) -> Result<domus_db::entities::Memory> {
        self.repos.memory.get(id).await
    }

    pub async fn assets(&self, id: Uuid) -> Result<Vec<domus_db::entities::Asset>> {
        let memory = self.repos.memory.get(id).await?;
        let asset_ids = self.repos.memory.asset_ids(id).await?;
        self.repos
            .asset
            .list_by_ids(memory.owner_id, &asset_ids)
            .await
    }

    pub async fn statistics(&self, user_id: Uuid) -> Result<serde_json::Value> {
        let memories = self.list(user_id).await?;
        Ok(serde_json::json!({ "total": memories.len() }))
    }
}

pub fn validate_on_this_day_data(data: &serde_json::Value) -> Result<i64> {
    let year = data
        .get("year")
        .and_then(serde_json::Value::as_i64)
        .ok_or_else(|| Error::BadRequest("data.year is required".into()))?;
    if !(1000..=9999).contains(&year) {
        return Err(Error::BadRequest(
            "data.year must be between 1000 and 9999".into(),
        ));
    }
    Ok(year)
}

pub fn validate_memory_update_has_fields(
    is_saved: Option<bool>,
    seen_at: Option<chrono::DateTime<chrono::Utc>>,
    memory_at: Option<chrono::DateTime<chrono::Utc>>,
) -> Result<()> {
    if is_saved.is_none() && seen_at.is_none() && memory_at.is_none() {
        return Err(Error::BadRequest(
            "At least one field must be provided".into(),
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{validate_memory_update_has_fields, validate_on_this_day_data};
    use serde_json::json;

    #[test]
    fn on_this_day_data_requires_a_valid_year_like_immich() {
        assert!(validate_on_this_day_data(&json!({})).is_err());
        assert!(validate_on_this_day_data(&json!({"year": 999})).is_err());
        assert!(validate_on_this_day_data(&json!({"year": 10000})).is_err());
        assert_eq!(
            validate_on_this_day_data(&json!({"year": 2020})).unwrap(),
            2020
        );
    }

    #[test]
    fn memory_update_requires_at_least_one_field_like_immich() {
        assert!(validate_memory_update_has_fields(None, None, None).is_err());
        assert!(validate_memory_update_has_fields(Some(true), None, None).is_ok());
    }
}
