//! "On this day" memories, generated by a nightly job.

#[allow(unused_imports)]
use domus_common::{Error, Result};
use domus_db::Repositories;
#[allow(unused_imports)]
use uuid::Uuid;

pub struct MemoryService {
    #[allow(dead_code)]
    repos: Repositories,
}

impl MemoryService {
    pub fn new(repos: Repositories) -> Self {
        Self { repos }
    }

    pub async fn list(&self, user_id: Uuid) -> Result<Vec<domus_db::entities::Memory>> {
        self.repos.memory.list_for_user(user_id).await
    }

    pub async fn get(&self, id: Uuid) -> Result<domus_db::entities::Memory> {
        self.repos.memory.get(id).await
    }
}
